apiVersion: v1

kind: Pod

metadata:
  name: apiadapter
  labels:
    app: apiadapter

spec:
  containers:
    - name: apiadapter-container
      image: mabdockerid/apiadapter:latest
      env:
      # contract address obtained from external/smartcontractaddress.txt from SmartContract docker
        - name: CONTRACT_ADDRESS
          value: "0x4D3D3B2922492093706d7f96FAd87DA99eC91A56"
      # cluster ip on the Qourum Node 2
        - name: RPC_ADDRESS
          value: "http://172.20.181.138:8545"
        - name: ACCOUNT
          value: "0x25211bfc3e3d5cc76f79841a0d43dd180c0ee5a7"
      ports:
        - containerPort: 3000
      imagePullPolicy: Always


---


apiVersion: v1
kind: Service
metadata:
  name: apiadapter-service
  labels:
    name: apiadapter-service

spec:
  selector:
    app: apiadapter

  ports:
    - port: 3000
      targetPort: 3000

  type: LoadBalancer


